//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentsCompany.DataFolder
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KKkuzminaEntities : DbContext
    {
        public static KKkuzminaEntities context;
        public KKkuzminaEntities()
            : base("name=KKkuzminaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public static KKkuzminaEntities GetContext()
        {
            if (context == null)
            {
                context = new KKkuzminaEntities();
            }
            return context;
        }

        public virtual DbSet<Partner> Partner { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Polzov> Polzov { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
