//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentsCompany.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int IdPayments { get; set; }
        public string ContractNumber { get; set; }
        public int IdPartner { get; set; }
        public int IdPolzov { get; set; }
        public string Summa { get; set; }
        public string Description { get; set; }
        public System.DateTime DateDogovora { get; set; }
    
        public virtual Partner Partner { get; set; }
        public virtual Polzov Polzov { get; set; }
    }
}
